version: "3.7"

services:
  subscriber_mqtt_1:
    container_name: subscriber_mqtt_1
    image: golfvert/wis2gb
    environment:
      - TZ=Europe/Paris
      - MQTT_SUB_BROKER=Broker_URL   # WIS2Node URL broker such as mqtts://broker.example.com:8883 or wss://broker.example.com:443
      - MQTT_SUB_USERNAME=
      - MQTT_SUB_PASSWORDD=
      - MQTT_SUB_TOPIC=Topic_to_sub   # e.g. wis2/a/origin/FRA/#
      - MQTT_PUB_BROKER=GlobalBroker_URL   # Global Broker URL such as mqtts://globalbroker.site.com:8883 or wss://globalbroker.site.com:443
      - MQTT_PUB_USERNAME=
      - MQTT_PUB_PASSWORD=
      - REDIS_URL=       # The list of all redis cluster member in an array format [{"host":@IP1,"port":port1},{"host":@IP2,"port":port2},......]
    ports:
      - "1880:1880"
    networks:
      - wis2relay
networks:
  wis2relay:
    driver: bridge
